apiVersion: signadot.com/v1
kind: SignadotResourcePlugin
metadata:
  name: sd-amazon-s3
spec:
  description: |
    Provision a temporary Amazon SQS bucket for use within a sandbox.

    Each sandbox resource request must specify a 'region' parameter,
    indicating the AWS region in which to provision the bucket (e.g. us-east-1).

    Each sandbox resource request can optionally specify 'args'
    that will be passed to the corresponding args in the 'aws s3 mb'
    command: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html

    The temporary bucket name will be available as the output key 'bucket-name'.
  type: ExecPod
  execPod:
    imageSpecVersion: v1.0
    template:
      metadata:
        namespace: {{ .Release.Namespace | quote }}
      spec:
        containers:
        - image: {{ .Values.image | quote }}
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          name: plugin
          env:
          - name: NAMESPACE
            value: {{ .Release.Namespace | quote }}
          volumeMounts:
          - name: aws-auth
            mountPath: /root/.aws
        volumes:
        - name: aws-auth
          secret:
            secretName: {{ .Values.awsAuthSecret | quote }}
