name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.8.1

      - name: Run chart-releaser (signadot-plugins)
        uses: helm/chart-releaser-action@v1.4.0
        with:
          charts_dir: signadot-plugins
          charts_repo_url: https://plugins.signadot.com
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Run chart-releaser (signadot-plugins-exp)
        uses: helm/chart-releaser-action@v1.4.0
        with:
          config: signadot-plugins-exp/chart-releaser.yaml
          charts_dir: signadot-plugins-exp
          charts_repo_url: https://plugins.signadot.com/exp
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
